server:
  port: 8082

cliente:
  service:
    url: http://localhost:8080/v1

spring:

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2